### ISSUE TITLE
'cannot override from' when running 'yarn deploy --greeting "Bonjour, le monde!"'

### ISSUE THREAD

**Issue by kootsZhin** [paulrberg/solidity-template#107]
The following error occurs when I run all the command, except for ```yarn clean```, and run ```yarn deploy --greeting "Bonjour, le monde!```.
```
An unexpected error occurred:

Error: cannot override from (operation="from", code=UNSUPPORTED_OPERATION, version=contracts/5.6.0)
    at Logger.makeError (/Users/michael/Github/max-ape/node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
    at Logger.throwError (/Users/michael/Github/max-ape/node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
    at /Users/michael/Github/max-ape/node_modules/@ethersproject/contracts/src.ts/index.ts:1204:20
    at Array.forEach (<anonymous>)
    at ContractFactory.getDeployTransaction (/Users/michael/Github/max-ape/node_modules/@ethersproject/contracts/src.ts/index.ts:1202:32)
    at ContractFactory.<anonymous> (/Users/michael/Github/max-ape/node_modules/@ethersproject/contracts/src.ts/index.ts:1246:53)
    at step (/Users/michael/Github/max-ape/node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Object.next (/Users/michael/Github/max-ape/node_modules/@ethersproject/contracts/lib/index.js:29:53)
    at fulfilled (/Users/michael/Github/max-ape/node_modules/@ethersproject/contracts/lib/index.js:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'cannot override from',
  code: 'UNSUPPORTED_OPERATION',
  operation: 'from'
}
```

**Comment by paulrberg** [comment]
Thanks for reporting, I fixed this in https://github.com/paulrberg/solidity-template/commit/b173741333327fc60c48317c0582e127f7765e97.
