### ISSUE TITLE
Error: The specified node does not exist

### ISSUE THREAD

**Issue by SvenMeyer** [paulrberg/solidity-template#47]
It's the 2nd time this error shows up (and I have no clue how I got there).

After the first time, I just `git clone ...` my own project from my github repo into a new directory, and it worked again.

Now I have this error again ... any idea ?

```
$ git commit -m "refactor: replace _isETHTrade & add _vestingStartTime in constructor parameter"
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 1s 319ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 1s 363ms
➤ YN0000: Done in 2s 803ms

✔ Preparing...
⚠ Running tasks...
  ❯ Running tasks for *.{js,json,md,sol,ts}
    ✖ prettier --config ./.prettierrc --write [FAILED]
↓ Skipped because of errors from tasks. [SKIPPED]
✔ Reverting to original state because of errors...
✔ Cleaning up...

✖ prettier --config ./.prettierrc --write:
[error] contracts/FixedSwap.sol: 
[error]     at StateVariableDeclarationContext.getChild (/home/sum/DEV/ETH/Project/fixed-swap-offchain-whitelist/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:9354:15)
[error]     at StateVariableDeclarationContext.getRuleContext (/home/sum/DEV/ETH/Project/fixed-swap-offchain-whitelist/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:9417:19)
[error]     at StateVariableDeclarationContext.identifier (/home/sum/DEV/ETH/Project/fixed-swap-offchain-whitelist/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:32243:17)
[error]     at ASTBuilder.visitStateVariableDeclaration (/home/sum/DEV/ETH/Project/fixed-swap-offchain-whitelist/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:35351:22)
[error]     at StateVariableDeclarationContext.accept (/home/sum/DEV/ETH/Project/fixed-swap-offchain-whitelist/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:32308:22)
[error]     at ASTBuilder.visit (/home/sum/DEV/ETH/Project/fixed-swap-offchain-whitelist/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:17669:19)
[error]     at ASTBuilder.visitContractPart (/home/sum/DEV/ETH/Project/fixed-swap-offchain-whitelist/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:35334:17)
[error]     at ContractPartContext.accept (/home/sum/DEV/ETH/Project/fixed-swap-offchain-whitelist/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:32232:22)
[error]     at ASTBuilder.visit (/home/sum/DEV/ETH/Project/fixed-swap-offchain-whitelist/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:17669:19)
[error]     at /home/sum/DEV/ETH/Project/fixed-swap-offchain-whitelist/node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/parser/dist/index.cjs.js:35344:52
husky - pre-commit hook exited with code 1 (error)

```

**Comment by paulrberg** [comment]
Looks like a linting issue that Prettier cannot fix automatically (the template uses Husky to run a hook on every git commit). Do you see any error or warning when you open the `FixedSwap.sol` contract in VSCode?

**Comment by SvenMeyer** [comment]
@paulrberg Thanks a lot for the hint.
Afters some stand alone prettier tests on the command line (with no additional helpful error messages), it turned out that I had a semicolon instead of a comma after one argument in a long list of constructor arguments !
Working now :-)

**Comment by danfinlay** [comment]
I'm getting this error, and I'd just like to say: It'd be great if errors included a line number.
